### ISSUE TITLE
no sensor shown

### ISSUE THREAD

**Issue by Krawinski** [flabbamann/aha_region#146]
Hi,
HA newbie from Wedemark here. . .
installet your resp AHA
but when i try to create a new card, no sensor for AHA is shown . . . just the HACS update sensor. . . 
i can't find my mistake
here is my config snipped:

sensor:
  # aha region waste sensors
  - platform: aha_region
    gemeinde: "Wedemark"
    strasse: "78800@Johann-Strauß-Weg / Abbensen@Abbensen"  #space 
    hausnr: 20

any idea ?

thx

**Comment by flabbamann** [comment]
Hi @Krawinski,
there are no collection dates listed on aha website for this address. Do you need to set `hausnraddon`?

**Comment by Krawinski** [comment]
nono 
thx for response
found your sensors
astonisht about german names....sensor.papier ;-)

**Comment by flabbamann** [comment]
Hm, I thought using the same names as on the website was less confusing than translating to english 😄. 
You can rename the sensors as you like.

I will close this now, as your issue is resolved.
