### ISSUE TITLE
no Sensor

### ISSUE THREAD

**Issue by mreinhold21** [flabbamann/aha_region#20]
Hello flabbamann, 
danke für eine intregation, leider funktioniert diese bei mir nicht. vielleicht kannst du mir helfen. 
- ordner unter custom_components ist erstellt.
- unter intregationen findet man diese auch, aber man kann diese ja nicht hinzufügen. => normal
- config angepasst mit einen werten... aber es wird kein neuer Sensor angelegt. 

Hätte da eine Idee. Mein Stadtteil hat umlaute. Könnte das vielleicht der Grund sein? 
Meine Strasse ist: "01923@Marthastr. / Wülfel@Wülfel"

Könntest du das vielleicht prüfen und mir Feedback geben. 
Danke für deine Hilfe.
Moritz

**Comment by flabbamann** [comment]
Hi Moritz,

hast du Home Assistant neu gestartet, nachdem du die Config angepasst hast? Die wird nicht automatisch geladen.
Umlaute _sollten_ eigentlich kein Problem sein.
Gibt es Fehler im Log?

Evtl hilft es auch das Debug-Logging für die Integration zu aktivieren:

```
# Configure Logging
logger:
  default: info
  logs:
    custom_components.aha_region: debug
```
Achtung, da wird die konfigurierte Adresse mit geloggt. Die möchtest du möglicherweise nicht hier posten 😉.

Was mir noch aufgefallen ist: Für die Straße gibt es zwei Einträge für Leichtverpackungen und die Integration zieht das falsche Datum. Ich denke das hat etwas mit der Umstellung auf Tonnen zu tun. Da ich grade nicht so super viel Zeit habe und sich das Problem wahrscheinlich in wenigen Wochen von alleine erledigt, ist es unwahrscheinlich, dass ich das vorher fixe 😉

**Comment by mreinhold21** [comment]
Hi Lars, 
danke für deine Antwort. 
Nun habe ich mich jedenfalls mal mit dem Thema Logs befassen können. 
Ja, ich habe mehrfach neu gestartet. (-:

Die Hausnummer habe ich jetzt noch mal zum X umgewandelt. Aber danke für deinen Hinweis. 
Ich hoffe, du kannst damit mehr anfangen als ich. Wenn du sagst, das es daran liegt, das aha gerade auf die gelben Tonnen umstellt, das sollte es vielleicht die anderen Werte gegeben. Aber ich erhalte gar keinen. 
Also, wenn du die Zeit finden solltest wäre das super. Aktuell lebe ich ja auch mit der App von aha. 
Also frohes Schaffen und danke für deine Hilfe. 

Gruß Moritz

-------
2022-11-08 22:24:45.231 DEBUG (MainThread) [custom_components.aha_region] Start async_update_data()
2022-11-08 22:24:45.231 DEBUG (MainThread) [custom_components.aha_region] Request data: {'gemeinde': 'Hannover', 'strasse': '01923@Marthastr. / Wülfel@Wülfel', 'hausnr': 'x', 'hausnraddon': 'a'}
-------
2022-11-08 22:24:47.272 DEBUG (MainThread) [custom_components.aha_region] Response: <ClientResponse(https://www.aha-region.de/abholtermine/abfuhrkalender) [200 OK]>
<CIMultiDictProxy('Date': 'Tue, 08 Nov 2022 21:24:46 GMT', 'Server': 'Apache', 'X-Powered-By': 'PHP/7.4.33', 'Content-Language': 'de', 'Cache-Control': 'private, no-store', 'Set-Cookie': 'fe_typo_user=95929b22b0b0f541f9cdbeb3d43e5a13; path=/; httponly; samesite=lax', 'Strict-Transport-Security': 'max-age=31536000', 'Access-Control-Allow-Origin': '*', 'Upgrade': 'h2', 'Connection': 'Upgrade', 'Cache-Control': 'max-age=0', 'Expires': 'Tue, 08 Nov 2022 21:24:46 GMT', 'Vary': 'Accept-Encoding,User-Agent', 'Content-Encoding': 'gzip', 'X-UA-Compatible': 'IE=edge', 'X-Content-Type-Options': 'nosniff', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html; charset=utf-8')>
-------
2022-11-08 22:24:47.655 ERROR (MainThread) [custom_components.aha_region] Unexpected error fetching aha Region data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/aha_region/coordinator.py", line 77, in _async_update_data
    response = await self.api.get_data()
  File "/config/custom_components/aha_region/coordinator.py", line 47, in get_data
    table = soup.find_all("table")[0]
IndexError: list index out of range
2022-11-08 22:24:47.661 DEBUG (MainThread) [custom_components.aha_region] Finished fetching aha Region data in 2.430 seconds (success: False)
-------
2022-11-08 22:25:51.210 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 414, in async_add_entities
    tasks = [
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 414, in <listcomp>
    tasks = [
  File "/config/custom_components/aha_region/sensor.py", line 62, in <genexpr>
    AhaWasteSensor(coordinator, wastetype) for wastetype in ABFALLARTEN
  File "/config/custom_components/aha_region/sensor.py", line 77, in __init__
    self._attr_native_value = self.coordinator.data[self._name]
-------

**Comment by flabbamann** [comment]
Hi Moritz,

da scheint gar kein Ergebnis gefunden zu werden. Kannst du bitte einmal prüfen, ob du zu der Adresse auf der aha-Webseite überhaupt etwas findest? Da lädt die Integration die Daten auch her.

Schöne Grüße,
Larts

**Comment by mreinhold21** [comment]
Hallo Lars, 
so hatte ich das auch verstanden, aber den CODE habe ich doch aus der Webseite heraus. 
siehe Link und screenshot. 
Oder mache ich hier etwas falsch? 
Danke für deine Hilfe. 

Gruß Moritz

link dazu: "view-source:https://www.aha-region.de/abholtermine/abfuhrkalender/?gemeinde=Hannover&von=M&bis=N#formular"

![Unbenannt](https://user-images.githubusercontent.com/50240338/200805318-ee39c04c-e833-4032-a7b9-902324851823.jpg)

**Comment by flabbamann** [comment]
Trage mal bitte in dem Formular auf der aha Webseite genau deine Adresse ein, also die Angaben die die auch in der Konfiguration gemacht hast. Gemeinde, Strasse, Hausnr und Hausnraddon. Und dann schau, ob dir die Webseite die Abholtermine liefert. Ich vermute, das ist nicht so und daher findet auch die Integration keine Termine.

**Comment by mreinhold21** [comment]
Hallo Lars, 
das funktioniert einwandfrei... die Hausnummer ist auch egal.. die Straße ist klein und es gibt für alle nur einen Termin. 
Du kannst hier von 1 bis 18 alle Nummern eintragen. 
Das mit dem gelben Sack/ neue Tonne, das gibt es halt auch bei mir. siehe Screenshot.

https://www.aha-region.de/abholtermine/abfuhrkalender/?gemeinde=Hannover&von=M&bis=N#formular
![Unbenannt](https://user-images.githubusercontent.com/50240338/200815868-d5b569dd-e4dd-48fc-97b1-3d8c85d8806b.jpg)

**Comment by mreinhold21** [comment]
Hallo Lars, 
gut das war es. Der optionale Wert muss leer sein. Damit hat es funktioniert. 
Und auch bei mir, werden die Leichtverpackungen nun erst im Januar abgeholt. 
Perfekt. Herzlichen Dank für deine Hilfe dabei.

**Comment by flabbamann** [comment]
Hallo Moritz,
schön, dass es jetzt bei dir läuft. Das mit den Leichtverpackungen regelt sich hoffentlich von selbst und ab Januar stimmen die Daten.

Ich bin offen für Vorschläge, wie ich die Beschreibung zur Konfiguration verbessern kann 🤔

Beste Grüße,
Lars

**Comment by mreinhold21** [comment]
Hallo Lars, 
sorry, hatte etwas wenig Zeit, war nur bei der Arbeit. 
Zu deiner Frage: Ergänzung zu deiner Doku, damit das Problem, was ich hatte, nicht noch einmal auftritt. 
"hausnraddon is optional, if this is not needed, it must be left empty, just as in the web page query. " 
Ein schönes Wochenende. Gruß Moritz
