### ISSUE TITLE
sensor.restabfall not provided at my location

### ISSUE THREAD

**Issue by TGSHAJ** [flabbamann/aha_region#58]
Hi,

first of all, thank you for this very cool integration!

Unfortunately I do not get the date for "Restabfall" collection at my location. Everything works fine with the example address provided. However I believe that aha seems to call the type of waste differently in Garbsen: "Restabfall 660/1.100 Liter". Would there be a way to use that information within the integration?

Thank you for your support!

**Comment by TGSHAJ** [comment]
Hi @flabbamann,
thank you for your response. Did you get the chance to find a solution for subject issue?
Thanks a lot and best regards

**Comment by flabbamann** [comment]
Hi @TGSHAJ,
It took a while, but it should work now. Could you verify this for your address by copying the latest files to your installation?

**Comment by TGSHAJ** [comment]
@flabbamann Thanks a lot! It works perfectly fine. I highly appreciate your support and all the effort you invested in this project.
