### ISSUE TITLE
Entität wird nicht mehr von der Integration aha_region bereitgestellt. 

### ISSUE THREAD

**Issue by EBobbbele** [flabbamann/aha_region#70]
Guten Morgen,

ich bekomme die unten angeführte Fehlermeldung. Eine Neuinstallation hat auch nicht zum Erfolg geführt. Manchmal wird das Datum angezeigt, manchmal erscheint diese Fehlermeldung. Woran könnte diess liegen. Nette Grüße

![image](https://github.com/flabbamann/aha_region/assets/125924294/76c8e20d-2aa0-4e80-a5ca-84f895b991bb)

**Comment by flabbamann** [comment]
Hi @EBobbbele, er versucht alle 12 Stunden die Daten neu zu laden und dabei geht etwas schief. Da es ja vorher funktioniert hat nehme ich mal an, dass du alles richtig konfiguriert hast. Funktioniert nur Restabfall nicht, oder alle Sensoren? Was steht in den Logs?

**Comment by EBobbbele** [comment]
Hallo Lars,

 

nett, dass du so schnell antwortest.

 

Ich habe nun Folgendes:

 



 

 

Deine Anwendung installiert.

 

Folgende Sensoren:





 

Offensichtlich zieht er sich die Daten.

 

IM HA habe ich folgendes eingestellt, dass ja normaler Weise auch funktionierte:

 



 

 

Als Fehlermeldungen kommt dieses:

 



 



 

Ich hoffe, dass hilft dir bzw. dann mir weiter.

 

Hier noch mein YAML-Eintrag:

 

sensor:

  # aha region waste sensors

  - platform: aha_region

    gemeinde: "Hemmingen"

    strasse: ***@***.*** Str. / ***@***.***"

    hausnr: 7

    abholplatz: "66086-0007 "

 

Vielen Dank für deine Mühen und dir einen schönen Sams- und Sonntag.

 

Nette Grüße

 

Boris

 

P. S.:

 

Fast alle perfekt:



 

 

 

Von: Lars ***@***.***> 
Gesendet: Freitag, 11. August 2023 14:29
An: flabbamann/aha_region ***@***.***>
Cc: EBobbbele ***@***.***>; Mention ***@***.***>
Betreff: Re: [flabbamann/aha_region] Entität wird nicht mehr von der Integration aha_region bereitgestellt. (Issue #70)

 

Hi @EBobbbele <https://github.com/EBobbbele> , er versucht alle 12 Stunden die Daten neu zu laden und dabei geht etwas schief. Da es ja vorher funktioniert hat nehme ich mal an, dass du alles richtig konfiguriert hast. Funktioniert nur Restabfall nicht, oder alle Sensoren? Was steht in den Logs?

**Comment by flabbamann** [comment]
Hi Boris, fehlen da irgendwie Bilder oder so? Vielleicht werden die rausgefiltert, wenn du per email antwortest...

**Comment by EBobbbele** [comment]
Siehe meinen korrigierten Eintrag von oben. Nette Grüße Boris

**Comment by flabbamann** [comment]
Ich habe ein neues Release fertig gemacht das den timeout erhöht und das Fehlerhandling verbessert. Ich hoffe solche Fehler treten dann nicht mehr auf.
